spring.application.name=fleet-maintenance-backend

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/fleet_maintenance
spring.datasource.username=postgres
spring.datasource.password=mahi@03

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration